"""MockAdapter — deterministic canned responses for offline testing.

Responses are keyed on the role and on marker words the round planner puts in
each prompt's objective ("gather", "challenge", "reconcile", "test both
sides", "review", "compose", "draft"). No randomness, no network, no cost.
"""

from __future__ import annotations

from ..models import Role
from ..registry import AdapterResult

FACTS = (
    "- SQLite offers atomic transactions and crash safety, even with concurrent writers.\n"
    "- Plain JSON files are human-readable and need no driver or schema.\n"
    "- Query and filtering needs (by status, by date) grow over time; SQLite handles them natively.\n"
    "- (uncertainty: expected write volume is assumed to be low)"
)

SOURCED_FACTS = (
    "- Claim: SQLite offers atomic transactions and crash safety. "
    "Source: local mock knowledge base. Confidence: 0.90\n"
    "- Claim: Plain JSON files are human-readable and need no driver or schema. "
    "Source: local mock knowledge base. Confidence: 0.80\n"
    "- Claim: Expected write volume is low. NO SOURCE FOUND - assumption. "
    "Confidence: 0.40"
)

CHALLENGE = (
    "DISAGREEMENT: storage backend — the researcher favors SQLite, but for a "
    "single-user local service plain JSON files are simpler, diff-able, and "
    "carry no binary-format lock-in."
)

VERDICT = (
    "VERDICT: uphold the original position. Evidence: session logs are "
    "append-heavy and queried by status; SQLite's transactions and indexed "
    "queries outweigh JSON simplicity, and the JSON-files position "
    "underestimates partial-write corruption risk."
)

RECONCILE = (
    "Reconciliation: keep SQLite as the primary store and mirror a "
    "human-readable JSONL trail per session — this captures the critic's "
    "readability concern without giving up transactional safety."
)

REVIEW = "Review: minor wording issues only; the draft is acceptable."

DRAFT = "DRAFT: Use SQLite as the primary store with a per-session JSONL mirror for readability."

DESIGN = "Design outline: one storage interface; SQLite implementation behind it; JSONL event mirror."

CODE_PLAN = "Implementation components: storage interface, SQLite store, JSONL mirror writer."

API_CONTRACT = "API contract: no external API required for this local storage decision."

RED_TEAM = "VERDICT: PASS. Residual risk: DB and JSONL mirror can drift if writes are not paired."

VALIDATION = (
    "CONFIRMED: SQLite offers atomic transactions and crash safety. "
    "Source: local mock knowledge base.\n"
    "CONFIRMED: Plain JSON files are human-readable. Source: local mock knowledge base.\n"
    "UNVERIFIABLE: Expected write volume is low. Reason: no workload data supplied."
)

LEAD_ARTIFACT = (
    "Here is the requested single-file app.\n\n"
    "ARTIFACT: index.html\n"
    "<!doctype html>\n"
    '<html lang="en">\n'
    '<head><meta charset="utf-8"><title>Mock App</title></head>\n'
    "<body><h1>Mock app</h1><p>Generated by the mock lead.</p></body>\n"
    "</html>\n"
)

LEAD_ANSWER = (
    "Lead answer: for this task the direct approach is sufficient; no specialist "
    "delegation was required."
)

# Returned when the lead is asked to CONTINUE a cut-off file — just the tail.
LEAD_CONTINUATION = "</body>\n</html>\n"

FINAL_JSON = (
    '{"answer": "Use SQLite for session logs, with a per-session JSONL mirror for human '
    'readability. SQLite gives atomic transactions, crash safety, and native querying; '
    'the JSONL mirror preserves the diff-ability that plain JSON files would have offered.", '
    '"confidence": "high", '
    '"assumptions": ["single local user", "modest write volume"], '
    '"risks_unresolved": ["JSONL mirror and DB could drift if writes are not paired"], '
    '"next_action": null}'
)


PANEL_VIEW = (
    "Panel view: SQLite is the safer default for session logs; watch the "
    "low-write-volume assumption and pair every DB write with its JSONL mirror line."
)


class MockAdapter:
    def __init__(self, name: str = "mock"):
        # A name per instance lets tests register several mock seats as a panel.
        self.name = name

    def call(self, role: Role, prompt: str, timeout_s: int,
             images: list[dict] | None = None) -> AdapterResult:
        lower = prompt.lower()
        if role == Role.panelist:
            content = PANEL_VIEW
        elif role == Role.lead:
            # A continuation request (truncated artifact) gets just the tail; any
            # other lead call gets a plain answer. The default mock lead does NOT
            # fabricate files — tests that exercise the artifact path register
            # their own adapter that emits an ARTIFACT: block.
            content = LEAD_CONTINUATION if ("cut off" in lower or "continuation" in lower) else LEAD_ANSWER
        elif role == Role.summarizer:
            content = FINAL_JSON
        elif role == Role.critic:
            if "rule this disagreement" in lower or "test both sides" in lower:
                content = VERDICT
            elif "review" in lower:
                content = REVIEW
            else:
                content = CHALLENGE
        elif role == Role.knowledge_retriever:
            content = SOURCED_FACTS
        elif role == Role.researcher:
            content = RECONCILE if "reconcile" in lower else FACTS
        elif role == Role.architect:
            content = DESIGN
        elif role == Role.code_generator:
            content = CODE_PLAN
        elif role == Role.api_integrator:
            content = API_CONTRACT
        elif role == Role.red_team:
            content = RED_TEAM
        elif role == Role.fact_validator:
            content = VALIDATION
        elif role == Role.implementer:
            content = DRAFT
        else:
            content = "(no contribution for this role)"
        return AdapterResult(content=content, duration_ms=1)

    def resume(self, resume_token: str, answer: str, timeout_s: int) -> AdapterResult:
        return AdapterResult(
            content=f"- Updated contribution incorporating the user's answer: {answer}",
            duration_ms=1,
        )
